MONDODB_URL = "localhost"
MONGODB_PORT = 27017

SECRET_KEY_FLASK = 'vez4b6te45tzebyzex5byze5yse5e4y'
PASSWORD_HASH_SALT = "h24yyszyzot4Eqtj=zr+hDXXuES4KN"

FULFILL_EXAMPLE_DATA = True

SESSION_TIME = 604800 # in seconds
#SESSION_TIME = 63600

PH_MIN_RANGE = 6.5
PH_MAX_RANGE = 9.5
PH_AVG = int((PH_MIN_RANGE + PH_MAX_RANGE) / 2)

TDS_MIN_RANGE = 50
TDS_MAX_RANGE = 100
TDS_AVG = (TDS_MIN_RANGE + TDS_MAX_RANGE) / 2
